import { defineConfig } from 'tsup'

export default defineConfig({
  // One entry per exports-map subpath. `internal/*` is deliberately excluded so
  // `zod-to-json-schema` never enters the runtime bundle.
  entry: [
    'src/index.ts',
    'src/schema.ts',
    'src/observations.ts',
    'src/diagnostics.ts',
    'src/fingerprint.ts',
    'src/contracts.ts',
    'src/detectors/index.ts',
    'src/providers/claude/index.ts',
    'src/providers/cline-cli/index.ts',
    'src/providers/codebuff/index.ts',
    'src/providers/codewhale/index.ts',
    'src/providers/codex/index.ts',
    'src/providers/grok/index.ts',
    'src/providers/kimi/index.ts',
    'src/providers/qwen/index.ts',
    'src/providers/zerostack/index.ts',
    'src/providers/droid/index.ts',
    'src/providers/mux/index.ts',
    'src/providers/openclaw/index.ts',
    'src/providers/open-design/index.ts',
    'src/providers/lingtai-tui/index.ts',
    'src/providers/gemini/index.ts',
    'src/providers/kimicode/index.ts',
    'src/providers/mistral-vibe/index.ts',
    'src/providers/pi/index.ts',
    'src/providers/crush/index.ts',
    'src/providers/zcode/index.ts',
    'src/providers/zed/index.ts',
    'src/providers/forge/index.ts',
    'src/providers/goose/index.ts',
    'src/providers/hermes/index.ts',
    'src/providers/warp/index.ts',
    'src/providers/cursor-agent/index.ts',
    'src/providers/cursor/index.ts',
    'src/providers/quickdesk/index.ts',
    'src/providers/devin/index.ts',
    'src/providers/copilot/index.ts',
    'src/providers/vscode-cline/index.ts',
    'src/providers/opencode-session/index.ts',
    'src/providers/antigravity/index.ts',
    'src/providers/kiro/index.ts',
    'src/providers/vercel-gateway/index.ts',
  ],
  format: ['esm'],
  target: 'node20',
  outDir: 'dist',
  clean: true,
  splitting: false,
  sourcemap: true,
  // Declarations come from `tsc -p tsconfig.build.json` instead. tsup's dts
  // worker bundles types for all 41 entries in one pass and exhausts the heap
  // (ERR_WORKER_OUT_OF_MEMORY) on Node 22 through 26.
  dts: false,
})
